/*----- PROTECTED REGION ID(SequencerConf::ClassFactory.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: ClassFactory.cpp,v 1.1 2013-11-15 08:15:09 graziano Exp $";
//=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible for the creation of
//               all class singleton for a device server. It is called
//               at device server startup.
//
// project :     Configurable Sequencer.
//
// $Author: graziano $
//
// $Revision: 1.1 $
// $Date: 2013-11-15 08:15:09 $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source: /home/cvsadm/cvsroot/fermi/servers/sequencerconf/src/ClassFactory.cpp,v $
// $Log: ClassFactory.cpp,v $
// Revision 1.1  2013-11-15 08:15:09  graziano
// first commit
//
//
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <tango.h>
#include <SequencerConfClass.h>

//	Add class header files if needed


/**
 *	Create SequencerConf Class singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
	//	Add method class init if needed
	
	add_class(SequencerConf_ns::SequencerConfClass::init("SequencerConf"));
}

/*----- PROTECTED REGION END -----*/
