/*----- PROTECTED REGION ID(SequencerConfStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: SequencerConfStateMachine.cpp,v 1.2 2013-11-19 14:58:56 graziano Exp $";
//=============================================================================
//
// file :        SequencerConfStateMachine.cpp
//
// description : C++ source for the �name� and its allowed
//               methods for commands and attributes
//
// project :     Configurable Sequencer.
//
// $Author: graziano $
//
// $Revision: 1.2 $
// $Date: 2013-11-19 14:58:56 $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source: /home/cvsadm/cvsroot/fermi/servers/sequencerconf/src/SequencerConfStateMachine.cpp,v $
// $Log: SequencerConfStateMachine.cpp,v $
// Revision 1.2  2013-11-19 14:58:56  graziano
// development
//
// Revision 1.1  2013-11-15 08:15:09  graziano
// first commit
//
//
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <SequencerConf.h>
#include <SequencerConfClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * SequencerConf states description:
 *
 */

namespace SequencerConf_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================
//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_Version_allowed()
 *	Description : Execution allowed for Version attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_Version_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Version attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_VersionAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_VersionAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_BoolScalarDynState_allowed()
 *	Description : Execution allowed for BoolScalarDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_BoolScalarDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for BoolScalarDyn attribute in READ access.
	
	/*----- PROTECTED REGION ID(SequencerConf::read_BoolScalarDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_BoolScalarDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_BoolSpectrumDynState_allowed()
 *	Description : Execution allowed for BoolSpectrumDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_BoolSpectrumDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for BoolSpectrumDyn attribute in READ access.
	
	/*----- PROTECTED REGION ID(SequencerConf::read_BoolSpectrumDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_BoolSpectrumDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_StringSpectrumDynState_allowed()
 *	Description : Execution allowed for StringSpectrumDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_StringSpectrumDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for StringSpectrumDyn attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_StringSpectrumDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_StringSpectrumDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_DoubleScalarDynState_allowed()
 *	Description : Execution allowed for DoubleScalarDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_DoubleScalarDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for DoubleScalarDyn attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_DoubleScalarDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_DoubleScalarDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_DoubleSpectrumDynState_allowed()
 *	Description : Execution allowed for DoubleSpectrumDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_DoubleSpectrumDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for DoubleSpectrumDyn attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_DoubleSpectrumDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_DoubleSpectrumDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_LongScalarDynState_allowed()
 *	Description : Execution allowed for LongScalarDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_LongScalarDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for LongScalarDyn attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_LongScalarDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_LongScalarDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_LongSpectrumDynState_allowed()
 *	Description : Execution allowed for LongSpectrumDyn attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_LongSpectrumDyn_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for LongSpectrumDyn attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_LongSpectrumDynStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_LongSpectrumDynStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_LogState_allowed()
 *	Description : Execution allowed for Log attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_Log_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Log attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_LogStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_LogStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_StepStatusState_allowed()
 *	Description : Execution allowed for StepStatus attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_StepStatus_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for StepStatus attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_StepStatusStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_StepStatusStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_StepErrorState_allowed()
 *	Description : Execution allowed for StepError attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_StepError_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for StepError attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_StepErrorStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_StepErrorStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_StepState_allowed()
 *	Description : Execution allowed for Step attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_Step_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for Step attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_StepStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_StepStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_RemainingTime_allowed()
 *	Description : Execution allowed for RemainingTime attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_RemainingTime_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for RemainingTime attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_RemainingTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_RemainingTimeStateAllowed_READ

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_ElapsedTime_allowed()
 *	Description : Execution allowed for ElapsedTime attribute.
 */
//--------------------------------------------------------

bool SequencerConf::is_ElapsedTime_allowed(Tango::AttReqType type)
{
		//	Not any excluded states for ElapsedTime attribute in READ access.

	/*----- PROTECTED REGION ID(SequencerConf::read_ElapsedTimeStateAllowed_READ) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::read_ElapsedTimeStateAllowed_READ

	return true;
}


	/*----- PROTECTED REGION ID(SequencerConf::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================
//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_Start_allowed()
 *	Description : Execution allowed for Start command.
 */
//--------------------------------------------------------

bool SequencerConf::is_Start_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Start command.

	/*----- PROTECTED REGION ID(SequencerConf::StartStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::StartStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_Stop_allowed()
 *	Description : Execution allowed for Stop command.
 */
//--------------------------------------------------------

bool SequencerConf::is_Stop_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Stop command.

	/*----- PROTECTED REGION ID(SequencerConf::StopStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::StopStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_Pause_allowed()
 *	Description : Execution allowed for Pause command.
 */
//--------------------------------------------------------

bool SequencerConf::is_Pause_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Pause command.

	/*----- PROTECTED REGION ID(SequencerConf::PauseStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::PauseStateAllowed

	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SequencerConf::is_Acknowledge_allowed()
 *	Description : Execution allowed for Acknowledge command.
 */
//--------------------------------------------------------

bool SequencerConf::is_Acknowledge_allowed(const CORBA::Any &any)
{
	//	Not any excluded states for Acknowledge command.

	/*----- PROTECTED REGION ID(SequencerConf::AcknowledgeStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::AcknowledgeStateAllowed

	return true;
}



	/*----- PROTECTED REGION ID(SequencerConf::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::are_dynamic_commands_allowed

}	// namespace SequencerConf_ns
