/*----- PROTECTED REGION ID(SequencerConfClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id: SequencerConfClass.cpp,v 1.2 2013-11-19 14:58:56 graziano Exp $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source: /home/cvsadm/cvsroot/fermi/servers/sequencerconf/src/SequencerConfClass.cpp,v $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        SequencerConfClass.cpp
//
// description : C++ source for the SequencerConfClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the �name� once per process.
//
// project :     Configurable Sequencer.
//
// $Author: graziano $
//
// $Revision: 1.2 $
// $Date: 2013-11-19 14:58:56 $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source: /home/cvsadm/cvsroot/fermi/servers/sequencerconf/src/SequencerConfClass.cpp,v $
// $Log: SequencerConfClass.cpp,v $
// Revision 1.2  2013-11-19 14:58:56  graziano
// development
//
// Revision 1.1  2013-11-15 08:15:09  graziano
// first commit
//
//
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SequencerConfClass.h>

/*----- PROTECTED REGION END -----*/

//-------------------------------------------------------------------
/**
 *	Create SequencerConfClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_SequencerConf_class(const char *name) {
		return SequencerConf_ns::SequencerConfClass::init(name);
	}
}


namespace SequencerConf_ns
{


//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SequencerConfClass *SequencerConfClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::SequencerConfClass(string &s)
 * description : 	constructor for the SequencerConfClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SequencerConfClass::SequencerConfClass(string &s):DeviceClass(s)
{
	cout2 << "Entering SequencerConfClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SequencerConf::Class::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::constructor

	cout2 << "Leaving SequencerConfClass constructor" << endl;
}


//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::~SequencerConfClass()
 * description : 	destructor for the SequencerConfClass
 */
//--------------------------------------------------------
SequencerConfClass::~SequencerConfClass()
{
	/*----- PROTECTED REGION ID(SequencerConf::Class::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SequencerConfClass *SequencerConfClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new SequencerConfClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SequencerConfClass *SequencerConfClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}




//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		Start::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "Start::execute(): arrived" << endl;


	((static_cast<SequencerConf *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		Stop::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "Stop::execute(): arrived" << endl;


	((static_cast<SequencerConf *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		Pause::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *PauseClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "Pause::execute(): arrived" << endl;


	((static_cast<SequencerConf *>(device))->pause());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		Acknowledge::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AcknowledgeClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "Acknowledge::execute(): arrived" << endl;


	((static_cast<SequencerConf *>(device))->acknowledge());
	return new CORBA::Any();
}



//===================================================================
//	Properties management
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::get_class_property
 * description : 	Get the class property for specified name.
 *
 * @param	name  The property name
 */
//--------------------------------------------------------
Tango::DbDatum SequencerConfClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::get_default_device_property()()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SequencerConfClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::get_default_class_property()()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SequencerConfClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::get_class_property()
 *	Description : //	Add your own code to initialize
 */
//--------------------------------------------------------
void SequencerConfClass::get_class_property()
{
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *	              For each property, add to wizard property name and description.
 *	              If default value has been set, add it to wizard property and.
 *	              store it in a DbDatum.
 */
//--------------------------------------------------------
void SequencerConfClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;
	
	//	Set Default Class Properties

	//	Set Default Device Properties

	prop_name = "Attr_config_prop";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Attr_config_file";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Polling_period";
	prop_desc = "";
	prop_def  = "-1";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "Read_timeout";
	prop_desc = "";
	prop_def  = "100";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "DefaultStepTimeout";
	prop_desc = "";
	prop_def  = "10000";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void SequencerConfClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Storage Ring Access");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename("SequencerConf");
	filename += "Class.cpp";
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}




//===================================================================
//	Factory methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::device_factory
 * description : 	Create the device object(s)
 *                  and store them in the device list
 *
 * @param	*devlist_ptr	The device name list
 */
//--------------------------------------------------------
void SequencerConfClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	/*----- PROTECTED REGION ID(SequencerConf::Class::device_factory_before) ENABLED START -----*/

	//	Add your own code
	cout <<__func__<< ": entering..." << endl;
	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new SequencerConf(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		SequencerConf *dev = static_cast<SequencerConf *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(SequencerConf::Class::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::device_factory_after

	
}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *	              and store them in the attribute list
 */
//--------------------------------------------------------
void SequencerConfClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SequencerConf::Class::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::attribute_factory_before


#if 0
	//	Attribute : BoolScalarDyn
	BoolScalarDynAttrib	*boolscalardyn = new BoolScalarDynAttrib();
	Tango::UserDefaultAttrProp	boolscalardyn_prop;
	//	description	not set for	BoolScalarDyn
	//	label	not set for	BoolScalarDyn
	//	unit	not set for	BoolScalarDyn
	//	standard_unit	not set for	BoolScalarDyn
	//	display_unit	not set for	BoolScalarDyn
	//	format	not set for	BoolScalarDyn
	//	max_value	not set for	BoolScalarDyn
	//	min_value	not set for	BoolScalarDyn
	//	max_alarm	not set for	BoolScalarDyn
	//	min_alarm	not set for	BoolScalarDyn
	//	max_warning	not set for	BoolScalarDyn
	//	min_warning	not set for	BoolScalarDyn
	//	delta_t	not set for	BoolScalarDyn
	//	delta_val	not set for	BoolScalarDyn
	boolscalardyn->set_default_properties(boolscalardyn_prop);
	//	Not Polled
	boolscalardyn->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	BoolScalarDyn does not fire change event
	//	BoolScalarDyn does not fire archive event
	//	BoolScalarDyn does not fire data_ready event
	att_list.push_back(boolscalardyn);

	//	Attribute : BoolSpectrumDyn
	BoolSpectrumDynAttrib	*boolspectrumdyn = new BoolSpectrumDynAttrib();
	Tango::UserDefaultAttrProp	boolspectrumdyn_prop;
	//	description	not set for	BoolSpectrumDyn
	//	label	not set for	BoolSpectrumDyn
	//	unit	not set for	BoolSpectrumDyn
	//	standard_unit	not set for	BoolSpectrumDyn
	//	display_unit	not set for	BoolSpectrumDyn
	//	format	not set for	BoolSpectrumDyn
	//	max_value	not set for	BoolSpectrumDyn
	//	min_value	not set for	BoolSpectrumDyn
	//	max_alarm	not set for	BoolSpectrumDyn
	//	min_alarm	not set for	BoolSpectrumDyn
	//	max_warning	not set for	BoolSpectrumDyn
	//	min_warning	not set for	BoolSpectrumDyn
	//	delta_t	not set for	BoolSpectrumDyn
	//	delta_val	not set for	BoolSpectrumDyn
	boolspectrumdyn->set_default_properties(boolspectrumdyn_prop);
	//	Not Polled
	boolspectrumdyn->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	BoolSpectrumDyn does not fire change event
	//	BoolSpectrumDyn does not fire archive event
	//	BoolSpectrumDyn does not fire data_ready event
	att_list.push_back(boolspectrumdyn);
#endif
	//	Attribute : Version
	VersionAttrib	*version = new VersionAttrib();
	Tango::UserDefaultAttrProp	version_prop;
	//	description	not set for	Version
	//	label	not set for	Version
	//	unit	not set for	Version
	//	standard_unit	not set for	Version
	//	display_unit	not set for	Version
	//	format	not set for	Version
	//	max_value	not set for	Version
	//	min_value	not set for	Version
	//	max_alarm	not set for	Version
	//	min_alarm	not set for	Version
	//	max_warning	not set for	Version
	//	min_warning	not set for	Version
	//	delta_t	not set for	Version
	//	delta_val	not set for	Version
	version->set_default_properties(version_prop);
	//	Not Polled
	version->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Version does not fire change event
	//	Version does not fire archive event
	//	Version does not fire data_ready event
	att_list.push_back(version);

	//	Attribute : Log
	LogAttrib	*log = new LogAttrib();
	Tango::UserDefaultAttrProp	log_prop;
	//	description	not set for	Log
	//	label	not set for	Log
	//	unit	not set for	Log
	//	standard_unit	not set for	Log
	//	display_unit	not set for	Log
	//	format	not set for	Log
	//	max_value	not set for	Log
	//	min_value	not set for	Log
	//	max_alarm	not set for	Log
	//	min_alarm	not set for	Log
	//	max_warning	not set for	Log
	//	min_warning	not set for	Log
	//	delta_t	not set for	Log
	//	delta_val	not set for	Log
	log->set_default_properties(log_prop);
	//	Not Polled
	log->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Log does not fire change event
	//	Log does not fire archive event
	//	Log does not fire data_ready event
	att_list.push_back(log);

	//	Attribute : StepStatus
	StepStatusAttrib	*step_status = new StepStatusAttrib();
	Tango::UserDefaultAttrProp	step_status_prop;
	//	description	not set for	StepStatus
	//	label	not set for	StepStatus
	//	unit	not set for	StepStatus
	//	standard_unit	not set for	StepStatus
	//	display_unit	not set for	StepStatus
	//	format	not set for	StepStatus
	//	max_value	not set for	StepStatus
	//	min_value	not set for	StepStatus
	//	max_alarm	not set for	StepStatus
	//	min_alarm	not set for	StepStatus
	//	max_warning	not set for	StepStatus
	//	min_warning	not set for	StepStatus
	//	delta_t	not set for	StepStatus
	//	delta_val	not set for	StepStatus
	step_status->set_default_properties(step_status_prop);
	//	Not Polled
	step_status->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	StepStatus does not fire change event
	//	StepStatus does not fire archive event
	//	StepStatus does not fire data_ready event
	att_list.push_back(step_status);

	//	Attribute : StepError
	StepErrorAttrib	*step_error = new StepErrorAttrib();
	Tango::UserDefaultAttrProp	step_error_prop;
	//	description	not set for	StepError
	//	label	not set for	StepError
	//	unit	not set for	StepError
	//	standard_unit	not set for	StepError
	//	display_unit	not set for	StepError
	//	format	not set for	StepError
	//	max_value	not set for	StepError
	//	min_value	not set for	StepError
	//	max_alarm	not set for	StepError
	//	min_alarm	not set for	StepError
	//	max_warning	not set for	StepError
	//	min_warning	not set for	StepError
	//	delta_t	not set for	StepError
	//	delta_val	not set for	StepError
	step_error->set_default_properties(step_error_prop);
	//	Not Polled
	step_error->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	StepError does not fire change event
	//	StepError does not fire archive event
	//	StepError does not fire data_ready event
	att_list.push_back(step_error);

	//	Attribute : Step
	StepAttrib	*step = new StepAttrib();
	Tango::UserDefaultAttrProp	step_prop;
	//	description	not set for	Step
	//	label	not set for	Step
	//	unit	not set for	Step
	//	standard_unit	not set for	Step
	//	display_unit	not set for	Step
	//	format	not set for	Step
	//	max_value	not set for	Step
	//	min_value	not set for	Step
	//	max_alarm	not set for	Step
	//	min_alarm	not set for	Step
	//	max_warning	not set for	Step
	//	min_warning	not set for	Step
	//	delta_t	not set for	Step
	//	delta_val	not set for	Step
	step->set_default_properties(step_prop);
	//	Not Polled
	step->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	Step does not fire change event
	//	Step does not fire archive event
	//	Step does not fire data_ready event
	att_list.push_back(step);

	//	Attribute : RemainingTime
	RemainingTimeAttrib	*remaining_time = new RemainingTimeAttrib();
	Tango::UserDefaultAttrProp	remaining_time_prop;
	//	description	not set for	RemainingTime
	//	label	not set for	RemainingTime
	remaining_time_prop.set_unit("s");
	remaining_time_prop.set_standard_unit("1");
	remaining_time_prop.set_display_unit("s");
	//	format	not set for	RemainingTime
	//	max_value	not set for	RemainingTime
	//	min_value	not set for	RemainingTime
	//	max_alarm	not set for	RemainingTime
	//	min_alarm	not set for	RemainingTime
	//	max_warning	not set for	RemainingTime
	//	min_warning	not set for	RemainingTime
	//	delta_t	not set for	RemainingTime
	//	delta_val	not set for	RemainingTime
	remaining_time->set_default_properties(remaining_time_prop);
	//	Not Polled
	remaining_time->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	RemainingTime does not fire change event
	//	RemainingTime does not fire archive event
	//	RemainingTime does not fire data_ready event
	att_list.push_back(remaining_time);

	//	Attribute : ElapsedTime
	ElapsedTimeAttrib	*elapsed_time = new ElapsedTimeAttrib();
	Tango::UserDefaultAttrProp	elapsed_time_prop;
	//	description	not set for	ElapsedTime
	//	label	not set for	ElapsedTime
	elapsed_time_prop.set_unit("s");
	elapsed_time_prop.set_standard_unit("1");
	elapsed_time_prop.set_display_unit("s");
	//	format	not set for	ElapsedTime
	//	max_value	not set for	ElapsedTime
	//	min_value	not set for	ElapsedTime
	//	max_alarm	not set for	ElapsedTime
	//	min_alarm	not set for	ElapsedTime
	//	max_warning	not set for	ElapsedTime
	//	min_warning	not set for	ElapsedTime
	//	delta_t	not set for	ElapsedTime
	//	delta_val	not set for	ElapsedTime
	elapsed_time->set_default_properties(elapsed_time_prop);
	//	Not Polled
	elapsed_time->set_disp_level(Tango::OPERATOR);
	//	Not memorized

	//	ElapsedTime does not fire change event
	//	ElapsedTime does not fire archive event
	//	ElapsedTime does not fire data_ready event
	att_list.push_back(elapsed_time);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());

	/*----- PROTECTED REGION ID(SequencerConf::Class::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::attribute_factory_after

}


//--------------------------------------------------------
/**
 *	Method      : SequencerConf::SequencerConfClass::command_factory()
 *	Description : Create the command object(s)
 *	              and store them in the command list
 */
//--------------------------------------------------------
void SequencerConfClass::command_factory()
{
	/*----- PROTECTED REGION ID(SequencerConf::Class::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::command_factory_before

	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);
	PauseClass	*pPauseCmd =
		new PauseClass("Pause",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pPauseCmd);
	AcknowledgeClass	*pAcknowledgeCmd =
		new AcknowledgeClass("Acknowledge",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAcknowledgeCmd);

	/*----- PROTECTED REGION ID(SequencerConf::Class::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::command_factory_after

}




//===================================================================
//	Dynamic attributes related methods
//===================================================================


//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void SequencerConfClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;


	/*----- PROTECTED REGION ID(SequencerConf::Class::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::create_static_att_list

}


//--------------------------------------------------------
/**
 * method : 		SequencerConfClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SequencerConfClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();
	//cout << __FUNCTION__<< ": entering..."<<endl;
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		SequencerConf *dev = static_cast<SequencerConf *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()],true);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SequencerConf::Class::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::erase_dynamic_attributes

}



	/*----- PROTECTED REGION ID(SequencerConf::Class::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	SequencerConf::Class::Additional Methods

} //	namespace
